server:
  port: 8083

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:mysql://localhost:3306/travel_booking_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# Feign client configuration
feign:
  clients:
    package-service:
      url: http://localhost:8082
    user-service:
      url: http://localhost:8081
    payment-service:
      url: http://localhost:8084

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  level:
    com.tpbs.bookingservice: DEBUG
    org.hibernate.SQL: DEBUG