# Review Service Configuration
server:
  port: 8087

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:mysql://localhost:3306/travel_review_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# Feign client configuration
feign:
  clients:
    user-service:
      url: http://localhost:8081
    package-service:
      url: http://localhost:8082
    booking-service:
      url: http://localhost:8083

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  level:
    com.tpbs.reviewservice: DEBUG